In [2]:
import numpy as np

class DenseLayer:
    def __init__(self, n_inputs, n_neurons):
        # Initialize small random weights and zero biases
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        # Perform the dot product and add biases
        self.output = np.dot(inputs, self.weights) + self.biases

# Example input: one sample with 3 features
inputs = np.array([[1.0, 2.0, 3.0]])

# Create a dense layer: 3 inputs → 2 neurons
layer = DenseLayer(3, 2)

# Forward pass
layer.forward(inputs)

print("Inputs:\n", inputs)
print("Weights:\n", layer.weights)
print("Biases:\n", layer.biases)
print("Output:\n", layer.output)


Inputs:
 [[1. 2. 3.]]
Weights:
 [[-0.05087974 -0.01340829]
 [-0.06025722  0.04242103]
 [ 0.05743984 -0.16639394]]
Biases:
 [[0. 0.]]
Output:
 [[ 0.00092533 -0.42774807]]
